![image.png](attachment:image.png)


Disponible en: http://groovychics.club/wp-content/uploads/2018/04/ohio-bird-calls-goldfinch-northwest-ohio-bird-calls.jpg

# PROYECTO 2: Image Classification with CNN

Blanca Ubaque - 201725992		
Carolina Trespalacios - 200313688		
Santiago Barco - 200913781		
Rafael Niño - 200522388		

# 1. Direct prediction
   * Download the dataset birds from http://www-cvr.ai.uiuc.edu/ponce_grp/data/.
   * Use [Keras](https://keras.io/) and a CNN from Keras [Applications](https://keras.io/applications/) pretrained on ImageNet, to classify the images in the birds dataset. Construct a confusion matrix that relates the bird classes with the 10 most frequent classes from ImageNet predicted by the model.
   * Discuss the results.

In [4]:
from keras.preprocessing import image
from keras.applications.inception_resnet_v2 \
    import preprocess_input
import numpy as np
import glob
import os
def load_data(path, pattern):
    class_names={}
    class_id=0
    x = []
    y = []
    for d in glob.glob(os.path.join(path, '*')):
        clname = os.path.basename(d)
        for f in glob.glob(os.path.join(d, pattern)): 
            if not clname in class_names:
                class_names[clname]=class_id 
                class_id += 1
            img = image.load_img(f, target_size=(224, 224))
            npi = image.img_to_array(img)     
            npi = preprocess_input(npi)
            x.append(npi)
            y.append(class_names[clname])
    return np.array(x), np.array(y), class_names

In [5]:
path = '../birds/'

In [6]:
x, y, class_names = load_data('birds', '*.jpg')

/Users/santiagobarcogomez/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 80000 bytes but only got 0. Skipping tag 64640
  " Skipping tag %s" % (size, len(data), tag))
/Users/santiagobarcogomez/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2652897280 bytes but only got 0. Skipping tag 2
  " Skipping tag %s" % (size, len(data), tag))
/Users/santiagobarcogomez/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2656043008 bytes but only got 0. Skipping tag 2
  " Skipping tag %s" % (size, len(data), tag))
/Users/santiagobarcogomez/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:692: UserWarning: Possibly corrupt EXIF data.  Expecting to read 65536 bytes but only got 0. Skipping tag 3
  " Skipping tag %s" % (size, len(data), tag))
/Users/santiagobar

In [7]:
print (x.shape, y.shape, len(class_names))

(600, 224, 224, 3) (600,) 6


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3,

In [9]:
print(x)

[[[[ 0.17647064  0.13725495  0.18431377]
   [-0.44313723 -0.51372552 -0.56862748]
   [-0.04313725 -0.11372548 -0.24705881]
   ..., 
   [-0.13725489 -0.13725489 -0.32549018]
   [-0.23137254 -0.19215685 -0.42745095]
   [-0.42745095 -0.34901959 -0.62352943]]

  [[-0.2235294  -0.25490195 -0.26274508]
   [-0.45098037 -0.51372552 -0.60000002]
   [-0.13725489 -0.19999999 -0.36470586]
   ..., 
   [-0.0745098  -0.08235294 -0.24705881]
   [-0.19999999 -0.16862744 -0.36470586]
   [-0.41960782 -0.34117645 -0.60784316]]

  [[-0.50588238 -0.52941179 -0.58431375]
   [ 0.06666672  0.01176476 -0.12941176]
   [-0.0745098  -0.12941176 -0.34901959]
   ..., 
   [-0.06666666 -0.0745098  -0.21568626]
   [-0.16862744 -0.13725489 -0.31764704]
   [-0.35686272 -0.28627449 -0.51372552]]

  ..., 
  [[-0.38823527 -0.38039213 -0.63137257]
   [-0.36470586 -0.33333331 -0.52941179]
   [-0.48235291 -0.42745095 -0.56862748]
   ..., 
   [-0.29411763 -0.26274508 -0.39607841]
   [-0.38823527 -0.36470586 -0.45098037]
   [-0.

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [11]:
print (X_train.shape, y_train.shape, len(class_names))

(420, 224, 224, 3) (420,) 6


In [12]:
print (X_test.shape, y_test.shape, len(class_names))

(180, 224, 224, 3) (180,) 6


In [13]:
X_train[0].shape

(224, 224, 3)

In [14]:
y_train

array([1, 2, 5, 4, 4, 3, 3, 4, 3, 2, 4, 5, 0, 2, 4, 2, 4, 3, 5, 1, 1, 4, 4,
       1, 2, 2, 2, 2, 2, 4, 5, 5, 5, 1, 2, 1, 3, 0, 5, 0, 1, 4, 0, 3, 3, 4,
       3, 3, 0, 3, 0, 4, 2, 4, 5, 0, 4, 2, 4, 2, 5, 3, 4, 1, 1, 3, 5, 4, 1,
       0, 1, 0, 1, 5, 0, 0, 3, 2, 0, 2, 2, 3, 5, 1, 3, 5, 2, 0, 1, 3, 3, 3,
       0, 0, 3, 5, 4, 0, 0, 5, 4, 0, 4, 4, 3, 4, 3, 2, 0, 4, 2, 0, 2, 0, 1,
       2, 5, 1, 5, 3, 1, 5, 5, 5, 0, 3, 1, 3, 1, 1, 1, 5, 3, 4, 3, 1, 3, 0,
       4, 5, 1, 3, 4, 4, 2, 3, 3, 3, 4, 0, 3, 0, 1, 2, 3, 5, 0, 1, 3, 3, 2,
       5, 2, 1, 2, 5, 5, 0, 4, 3, 1, 3, 1, 4, 5, 1, 4, 3, 3, 5, 1, 5, 0, 1,
       2, 4, 0, 3, 2, 2, 4, 1, 1, 2, 3, 2, 5, 4, 4, 4, 5, 3, 1, 5, 2, 3, 0,
       2, 1, 5, 3, 4, 5, 3, 5, 4, 3, 5, 2, 5, 4, 4, 1, 1, 4, 4, 4, 3, 3, 1,
       5, 2, 3, 5, 1, 3, 1, 4, 1, 5, 2, 2, 1, 1, 4, 3, 3, 2, 5, 4, 3, 1, 5,
       2, 5, 0, 1, 5, 4, 1, 4, 0, 1, 0, 2, 0, 2, 1, 3, 1, 0, 0, 0, 1, 1, 2,
       4, 4, 2, 5, 0, 0, 2, 5, 3, 5, 1, 4, 5, 0, 5, 5, 2, 3, 2, 3, 3, 2, 2,
       0, 2,

In [15]:
from keras.datasets import cifar10
from keras.utils import np_utils
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from livelossplot import PlotLossesKeras

### Categorias de las clases de Y

In [15]:
from keras.utils import np_utils
nb_classes = y_train.max() + 1
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

In [16]:
nb_classes

6

### 1.1 Modelo con Keras

In [17]:
from keras.layers import Dropout

model = Sequential()
model.add(Flatten(input_shape=(224,224,3)))
model.add(Dense(6))
model.add(Activation('softmax'))

model.add(Dropout(0.2))
model.add(Dense(6))
model.add(Activation('softmax'))
#model.summary(70)

In [18]:
from keras.optimizers import SGD

model.compile(loss='categorical_crossentropy',
              optimizer=SGD(),
              metrics=['accuracy'])

In [19]:
model.fit(X_train,Y_train,epochs=60,verbose=2)

Epoch 1/60
 - 1s - loss: 1.7248 - acc: 0.2190
Epoch 2/60
 - 1s - loss: 1.6641 - acc: 0.2524
Epoch 3/60
 - 0s - loss: 1.6505 - acc: 0.2929
Epoch 4/60
 - 0s - loss: 1.6183 - acc: 0.3357
Epoch 5/60
 - 1s - loss: 1.6003 - acc: 0.3667
Epoch 6/60
 - 0s - loss: 1.5987 - acc: 0.3452
Epoch 7/60
 - 0s - loss: 1.6428 - acc: 0.3643
Epoch 8/60
 - 0s - loss: 1.5984 - acc: 0.3619
Epoch 9/60
 - 0s - loss: 1.5811 - acc: 0.3762
Epoch 10/60
 - 0s - loss: 1.5621 - acc: 0.4333
Epoch 11/60
 - 0s - loss: 1.5525 - acc: 0.4143
Epoch 12/60
 - 0s - loss: 1.5465 - acc: 0.4167
Epoch 13/60
 - 0s - loss: 1.5264 - acc: 0.4548
Epoch 14/60
 - 0s - loss: 1.5378 - acc: 0.4190
Epoch 15/60
 - 0s - loss: 1.5052 - acc: 0.4524
Epoch 16/60
 - 0s - loss: 1.5033 - acc: 0.4524
Epoch 17/60
 - 0s - loss: 1.5084 - acc: 0.4548
Epoch 18/60
 - 0s - loss: 1.4796 - acc: 0.4714
Epoch 19/60
 - 0s - loss: 1.4811 - acc: 0.4595
Epoch 20/60
 - 0s - loss: 1.4740 - acc: 0.4714
Epoch 21/60
 - 0s - loss: 1.4550 - acc: 0.4881
Epoch 22/60
 - 0s - lo

In [20]:
# make predictions for testing set
y_pred = model.predict_classes(X_test)
y_pred

array([4, 2, 5, 3, 3, 2, 2, 2, 2, 3, 2, 4, 4, 5, 3, 2, 5, 2, 4, 2, 3, 3,
       1, 5, 3, 1, 2, 4, 1, 4, 4, 2, 4, 2, 4, 4, 2, 1, 4, 4, 3, 2, 5, 3,
       4, 3, 4, 2, 0, 3, 1, 2, 4, 3, 3, 2, 2, 5, 3, 4, 0, 4, 4, 5, 5, 2,
       5, 5, 2, 3, 1, 2, 2, 4, 4, 3, 1, 3, 1, 4, 2, 4, 5, 5, 2, 3, 4, 2,
       3, 2, 2, 3, 2, 2, 2, 2, 2, 3, 4, 3, 2, 2, 5, 3, 0, 4, 1, 2, 2, 4,
       4, 4, 3, 5, 3, 3, 5, 1, 4, 4, 3, 0, 3, 5, 4, 1, 5, 2, 3, 4, 4, 1,
       1, 4, 5, 4, 2, 2, 2, 2, 4, 2, 5, 3, 4, 4, 3, 4, 2, 5, 5, 0, 5, 5,
       3, 4, 2, 4, 2, 2, 3, 2, 3, 4, 5, 4, 4, 2, 5, 2, 1, 2, 5, 4, 4, 2,
       4, 2, 4, 2], dtype=int64)

In [21]:
Ynew=Y_test.argmax(axis=1)

In [22]:
Ynew

array([1, 4, 5, 0, 1, 2, 0, 4, 0, 3, 0, 1, 1, 5, 3, 2, 0, 2, 1, 0, 0, 5,
       5, 5, 3, 5, 0, 1, 5, 4, 5, 1, 0, 2, 1, 4, 1, 5, 4, 2, 3, 0, 5, 5,
       0, 1, 4, 1, 0, 4, 2, 2, 1, 5, 5, 3, 2, 1, 1, 1, 0, 1, 3, 5, 5, 0,
       5, 5, 0, 3, 3, 0, 4, 3, 4, 5, 3, 2, 5, 4, 2, 4, 5, 3, 0, 0, 1, 2,
       3, 2, 2, 5, 0, 3, 2, 2, 2, 0, 4, 0, 0, 2, 5, 3, 0, 4, 1, 2, 2, 4,
       1, 4, 5, 5, 3, 3, 3, 1, 4, 4, 1, 0, 3, 5, 1, 1, 5, 2, 5, 4, 0, 5,
       1, 1, 4, 1, 0, 0, 2, 0, 0, 2, 1, 0, 4, 1, 3, 4, 0, 0, 5, 5, 3, 3,
       5, 2, 0, 4, 1, 0, 3, 2, 0, 4, 3, 1, 2, 2, 5, 3, 2, 2, 5, 4, 1, 0,
       4, 0, 0, 2], dtype=int64)

In [23]:
Y_test

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

In [24]:
print('The accuracy of the model is ',(y_pred==Ynew).mean())

The accuracy of the model is  0.4388888888888889


In [25]:
## PERFORMANCE DE MODELO
score = model.evaluate(X_test, Y_test)

180/180 [==============================] - 0s 623us/step


In [26]:
print('Test score:', score[0])
print('Test accuracy:', score[1])

Test score: 1.5188979307810466
Test accuracy: 0.4388888888888889


In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 4,  0, 20,  7,  5,  2],
       [ 0,  4,  4,  4, 17,  2],
       [ 0,  2, 23,  1,  3,  0],
       [ 0,  2,  3, 12,  2,  5],
       [ 0,  0,  3,  1, 20,  1],
       [ 1,  6,  0,  9,  1, 16]], dtype=int64)

In [28]:
from collections import Counter

c = Counter(Ynew)
c
print('Counter de Test:', c)
print('Counter de Test:', c.most_common(10))

Counter de Test: Counter({0: 38, 5: 33, 1: 31, 2: 29, 4: 25, 3: 24})
Counter de Test: [(0, 38), (5, 33), (1, 31), (2, 29), (4, 25), (3, 24)]


In [29]:
d = Counter(y_pred)
d
print('Counter de Predic:', d)
print('Counter de Predic:', d.most_common(10))

Counter de Predic: Counter({2: 53, 4: 48, 3: 34, 5: 26, 1: 14, 0: 5})
Counter de Predic: [(2, 53), (4, 48), (3, 34), (5, 26), (1, 14), (0, 5)]


### Conclusiones

Al correr el modelo se verifica que las categpias mas comunes en el TEST son 0, 5 y 1, sin embargo el modelo usado muestra las categorías más comunes como 4, 5 y 3, lo que indica que no es un modelo que nos permita un hacer una clasificación correcta.


### 1.2 Modelo con Keras VGG con ImageNet

In [30]:
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np

In [31]:
from keras.applications import VGG16
from keras.applications.imagenet_utils import preprocess_input, decode_predictions
import os

In [32]:
import pandas as pd
import os
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import r2_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from skimage import io
from tqdm import tqdm
import os
%matplotlib inline

In [33]:
from keras.datasets import cifar10
from keras.utils import np_utils
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

In [34]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from livelossplot import PlotLossesKeras

# `keras.applications para Birds`

In [35]:
from keras.applications import VGG16
from keras.applications.imagenet_utils import preprocess_input, decode_predictions
import os

In [36]:
vgg16 = VGG16(include_top=False, weights='imagenet')
print('Model loaded.')

Model loaded.


In [37]:
vgg16.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, None, None, 3)     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, None, None, 64)    1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, None, None, 64)    36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, None, None, 64)    0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, None, None, 128)   73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, None, None, 128)   147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, None, None, 128)   0         
__________

In [38]:
from keras.preprocessing import image
import numpy as np

In [39]:
X_train.shape

(420, 224, 224, 3)

In [40]:
X_vgg_train = vgg16.predict(X_train)

In [41]:
X_vgg_train.shape

(420, 7, 7, 512)

In [45]:
X_vgg_train

array([[[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 5.1599199e-01, 0.0000000e+00],
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 3.9582419e-01, 0.0000000e+00],
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 7.2050589e-01, 7.2830483e-02],
         ...,
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 2.9240865e-01, 0.0000000e+00],
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 3.7691686e-01, 0.0000000e+00],
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 6.0063607e-01, 0.0000000e+00]],

        [[0.0000000e+00, 0.0000000e+00, 6.2320781e-01, ...,
          0.0000000e+00, 1.4702469e-01, 0.0000000e+00],
         [1.4509211e+00, 9.7670197e-02, 3.9996248e-01, ...,
          0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
         [1.7168244e+00, 0.0000000e+00, 3.4954864e-01, .

In [43]:
X_vgg_test = vgg16.predict(X_test)

In [46]:
X_vgg_test.shape

(180, 7, 7, 512)

In [47]:
X_vgg_test

array([[[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          1.6525269e-01, 1.0369571e+00, 0.0000000e+00],
         [4.2943317e-01, 0.0000000e+00, 4.6850502e-02, ...,
          0.0000000e+00, 1.0474889e+00, 0.0000000e+00],
         [3.1198967e-01, 0.0000000e+00, 1.2692671e+00, ...,
          0.0000000e+00, 1.0980147e-01, 4.3697622e-01],
         ...,
         [0.0000000e+00, 0.0000000e+00, 4.6280950e-01, ...,
          5.0966513e-01, 2.4377716e-01, 0.0000000e+00],
         [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 5.7386374e-01, 0.0000000e+00],
         [1.4385232e-01, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 7.8386766e-01, 0.0000000e+00]],

        [[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
          0.0000000e+00, 9.0998590e-01, 0.0000000e+00],
         [2.0488900e-01, 2.2134000e-01, 1.3997452e+00, ...,
          1.9112352e-01, 7.8889084e-01, 0.0000000e+00],
         [6.1406863e-01, 0.0000000e+00, 1.5531700e+00, .

In [48]:
model3 = Sequential()

model3.add(Flatten(input_shape=(7,7,512)))
model3.add(Dense(512, activation='relu'))
model3.add(Dropout(0.5))
model3.add(Dense(6, activation='softmax'))

In [49]:
model3.compile("rmsprop", "categorical_crossentropy", metrics=["accuracy"])

In [50]:
model3.fit(X_vgg_train,Y_train,epochs=30,verbose=2)

Epoch 1/30
 - 3s - loss: 10.4372 - acc: 0.2333
Epoch 2/30
 - 3s - loss: 9.0829 - acc: 0.3500
Epoch 3/30
 - 3s - loss: 7.0951 - acc: 0.5095
Epoch 4/30
 - 3s - loss: 6.1639 - acc: 0.5833
Epoch 5/30
 - 3s - loss: 5.1215 - acc: 0.6119
Epoch 6/30
 - 3s - loss: 3.5818 - acc: 0.6643
Epoch 7/30
 - 3s - loss: 1.1367 - acc: 0.8476
Epoch 8/30
 - 3s - loss: 0.3283 - acc: 0.9476
Epoch 9/30
 - 3s - loss: 0.4269 - acc: 0.9262
Epoch 10/30
 - 3s - loss: 0.5789 - acc: 0.9143
Epoch 11/30
 - 3s - loss: 0.3202 - acc: 0.9405
Epoch 12/30
 - 3s - loss: 0.1834 - acc: 0.9714
Epoch 13/30
 - 3s - loss: 0.0861 - acc: 0.9738
Epoch 14/30
 - 3s - loss: 0.0874 - acc: 0.9786
Epoch 15/30
 - 3s - loss: 0.1649 - acc: 0.9738
Epoch 16/30
 - 3s - loss: 0.1700 - acc: 0.9667
Epoch 17/30
 - 3s - loss: 0.0394 - acc: 0.9905
Epoch 18/30
 - 3s - loss: 0.0534 - acc: 0.9857
Epoch 19/30
 - 3s - loss: 0.0769 - acc: 0.9833
Epoch 20/30
 - 3s - loss: 0.1088 - acc: 0.9833
Epoch 21/30
 - 3s - loss: 0.1038 - acc: 0.9881
Epoch 22/30
 - 4s - l

In [51]:
# make predictions for testing set
y_pred = model3.predict_classes(X_vgg_test)
y_pred

array([1, 4, 5, 0, 1, 2, 0, 4, 0, 3, 0, 1, 1, 5, 3, 2, 0, 2, 1, 0, 0, 5,
       5, 5, 3, 5, 0, 1, 5, 4, 5, 1, 0, 2, 1, 4, 1, 5, 4, 2, 3, 0, 5, 5,
       0, 1, 4, 1, 0, 4, 2, 2, 1, 5, 5, 3, 2, 1, 1, 1, 0, 1, 1, 5, 5, 0,
       1, 1, 0, 3, 3, 0, 4, 3, 3, 5, 3, 2, 5, 4, 2, 4, 5, 3, 0, 0, 1, 2,
       3, 2, 2, 5, 0, 3, 2, 2, 2, 0, 1, 0, 0, 2, 5, 3, 0, 4, 1, 2, 2, 4,
       1, 4, 5, 5, 3, 3, 3, 1, 4, 4, 1, 0, 3, 5, 1, 1, 5, 2, 5, 4, 0, 5,
       1, 1, 4, 1, 0, 0, 2, 4, 0, 2, 1, 0, 4, 1, 3, 4, 0, 1, 5, 5, 3, 3,
       5, 2, 0, 4, 3, 0, 3, 2, 0, 4, 3, 1, 2, 2, 5, 3, 2, 2, 5, 4, 1, 0,
       1, 0, 0, 2], dtype=int64)

In [52]:
Ynew=Y_test.argmax(axis=1)

In [53]:
print('The accuracy of the model vgg is ',(y_pred==Ynew).mean())

The accuracy of the model vgg is  0.95


In [54]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[36,  1,  0,  0,  1,  0],
       [ 0, 30,  0,  1,  0,  0],
       [ 0,  0, 29,  0,  0,  0],
       [ 0,  1,  0, 23,  0,  0],
       [ 0,  2,  0,  1, 22,  0],
       [ 0,  2,  0,  0,  0, 31]], dtype=int64)

In [55]:
from collections import Counter

e = Counter(Ynew)
e
print('Counter de Test:', e)
print('Counter de Test:', e.most_common(10))

Counter de Test: Counter({0: 38, 5: 33, 1: 31, 2: 29, 4: 25, 3: 24})
Counter de Test: [(0, 38), (5, 33), (1, 31), (2, 29), (4, 25), (3, 24)]


In [56]:
f = Counter(y_pred)
f
print('Counter de Predic:', f)
print('Counter de Predic:', f.most_common(10))

Counter de Predic: Counter({1: 36, 0: 36, 5: 31, 2: 29, 3: 25, 4: 23})
Counter de Predic: [(1, 36), (0, 36), (5, 31), (2, 29), (3, 25), (4, 23)]


### 1.2 Modelo con Keras VGG con ImageNet CONCLUSIONES de VGG con IMAGENET 


Para este caso se observa que las categorías con más datos son la 0, la 5 y la 1, para el caso de los datos de TEST en la la variable de predicción, y al compararla con el resultado de la predicción del modelo se observa que son las categorias 1, 0 y 5, es decir que las categorias 1 0 y 5, son las que no son acertadas según el accuracy del modelo.

### 1.1 Modelo con Keras CONCLUSIONES

* La muestra se tomo de manera aleatoria para que exista representación de cada grupo de pajaros
* El modelo con VGG16 muestra un accuracy de 0.43 
* El modelo con Keras muestra un accuracy de 0.95
* Con el modelo de VGG16 muestra mejor clasificación por que se toma como base una red pre entrenada.


# 2. Transfer learning
   * Use the pre-trained CNN model as a feature extractor. Create a new model that replaces the top part of the pretrained CNN with two layers of 256 and 6 neurons respectively.
   * Train the model with the training images from the bird dataset. 
   * Evaluate the performance over the test dataset reporting the results in a confusion matrix. Discuss the results.

In [90]:
from keras.utils import np_utils
nb_classes = y_train.max() + 1
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

In [58]:
X_train.shape

(420, 224, 224, 3)

In [59]:
from keras.applications.vgg16 import VGG16
model_vgg16 = VGG16(weights='imagenet', include_top=False)

In [60]:
predict=model_vgg16.predict(X_train)

In [61]:
predict.shape

(420, 7, 7, 512)

In [62]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

model = Sequential()
model.add(Flatten(input_shape=(7,7,512)))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(6, activation='softmax'))
model.compile("rmsprop", "categorical_crossentropy", metrics=["accuracy"])

In [63]:
model.fit(predict,Y_train,epochs=50,verbose=2)

Epoch 1/50
 - 3s - loss: 11.5169 - acc: 0.1833
Epoch 2/50
 - 3s - loss: 7.7056 - acc: 0.4071
Epoch 3/50
 - 3s - loss: 4.5492 - acc: 0.6452
Epoch 4/50
 - 3s - loss: 3.8922 - acc: 0.6929
Epoch 5/50
 - 3s - loss: 3.1271 - acc: 0.7738
Epoch 6/50
 - 3s - loss: 3.1736 - acc: 0.7619
Epoch 7/50
 - 3s - loss: 2.9226 - acc: 0.7976
Epoch 8/50
 - 3s - loss: 2.3675 - acc: 0.7881
Epoch 9/50
 - 3s - loss: 0.9497 - acc: 0.8595
Epoch 10/50
 - 3s - loss: 0.4630 - acc: 0.9405
Epoch 11/50
 - 3s - loss: 0.4458 - acc: 0.9286
Epoch 12/50
 - 4s - loss: 0.4025 - acc: 0.9381
Epoch 13/50
 - 4s - loss: 0.0739 - acc: 0.9857
Epoch 14/50
 - 4s - loss: 0.2429 - acc: 0.9571
Epoch 15/50
 - 4s - loss: 0.0570 - acc: 0.9810
Epoch 16/50
 - 4s - loss: 0.0079 - acc: 0.9952
Epoch 17/50
 - 4s - loss: 0.2717 - acc: 0.9571
Epoch 18/50
 - 4s - loss: 0.0279 - acc: 0.9929
Epoch 19/50
 - 4s - loss: 0.3799 - acc: 0.9452
Epoch 20/50
 - 4s - loss: 0.0927 - acc: 0.9810
Epoch 21/50
 - 4s - loss: 0.1808 - acc: 0.9595
Epoch 22/50
 - 4s - l

In [64]:
x_test_new = model_vgg16.predict(X_test)

In [65]:
# make predictions for testing set
y_pred = model.predict_classes(x_test_new)
y_pred

array([1, 4, 5, 0, 1, 2, 0, 4, 0, 3, 0, 1, 1, 5, 3, 2, 0, 2, 1, 0, 0, 1,
       1, 1, 3, 1, 0, 1, 5, 4, 5, 1, 0, 2, 1, 4, 1, 5, 4, 2, 3, 0, 1, 4,
       0, 1, 4, 1, 0, 4, 2, 2, 1, 1, 5, 3, 2, 1, 1, 1, 0, 1, 1, 5, 5, 0,
       1, 1, 0, 3, 3, 0, 4, 3, 3, 1, 3, 2, 5, 4, 2, 4, 5, 3, 0, 0, 1, 2,
       3, 2, 2, 5, 0, 3, 2, 2, 2, 0, 4, 0, 3, 2, 5, 3, 0, 4, 1, 2, 2, 4,
       1, 4, 1, 5, 3, 3, 3, 1, 4, 4, 1, 0, 3, 5, 1, 1, 5, 2, 1, 4, 0, 1,
       1, 1, 4, 1, 0, 0, 2, 0, 0, 2, 1, 0, 4, 1, 3, 4, 0, 0, 5, 1, 3, 3,
       5, 2, 0, 4, 1, 0, 3, 2, 0, 4, 3, 1, 2, 2, 3, 3, 2, 2, 1, 4, 1, 0,
       4, 0, 0, 2], dtype=int64)

In [66]:
Ynew=Y_test.argmax(axis=1)

In [67]:
print('The accuracy of the model is ',(y_pred==Ynew).mean())

The accuracy of the model is  0.8944444444444445


In [68]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[37,  0,  0,  1,  0,  0],
       [ 0, 31,  0,  0,  0,  0],
       [ 0,  0, 29,  0,  0,  0],
       [ 0,  1,  0, 23,  0,  0],
       [ 0,  0,  0,  1, 24,  0],
       [ 0, 14,  0,  1,  1, 17]], dtype=int64)

### 2.1. Modelo con Trasnfer Learning CONCLUSIONES


* Al utilizar Activación (SoftMax) se usa la capa final que actúa básicamente como un normalizador y ayuda a asignar 
la clasificación  que corresponda con una clase en especifica de pajaritos.

* El algoritmo obtuvo una precisión de prueba 0.89

# 3. Fine tuning
   * Repeat the experiment from the last question, but this time allow all the layers to be trained. 
   * Compare and discuss the results.

In [26]:
from tensorflow.python.keras.models import Model, Sequential
from tensorflow.python.keras.layers import Dense, Flatten, Dropout
from tensorflow.python.keras.applications import VGG16
from tensorflow.python.keras.applications.vgg16 import preprocess_input, decode_predictions
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.optimizers import Adam, RMSprop
import numpy as np


In [ ]:
from keras.utils import np_utils
y_train_vgg = np_utils.to_categorical(y_train,6)
y_test_vgg = np_utils.to_categorical(y_test,6)

En esta sección se realizara la carga de la ultima capa del modelo pre-entrenado VGG, con el fin de realizar el ajuste de la ultima capa por medio de codigo.

In [66]:
# build the VGG16 network
model = VGG16(include_top=True, weights='imagenet')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

Se tomara la capa 5 para realizar el proceso de **Trasnfer Learning**, asi que se determianra el Shape adecuado para dicho tranfer.

In [67]:
transfer_layer_vgg = model.get_layer('block5_pool')

In [68]:
transfer_layer_vgg.output

<tf.Tensor 'block5_pool_3/MaxPool:0' shape=(?, 7, 7, 512) dtype=float32>

In [69]:
input_shape = model.layers[0].output_shape[1:3]
input_shape

(224, 224)

In [70]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [71]:
transfer_layer = model.get_layer('block5_pool')

In [72]:
transfer_layer.output

<tf.Tensor 'block5_pool_3/MaxPool:0' shape=(?, 7, 7, 512) dtype=float32>

Con el siguiente cogido se acotara el modelo.

In [73]:
conv_model = Model(inputs=model.input,
                   outputs=transfer_layer.output)

In [74]:
conv_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

En este punto se hara el modelo de "Transfer Learning"

In [77]:
# Start a new Keras Sequential model.
new_model = Sequential()

# Add the convolutional part of the VGG16 model from above.
new_model.add(conv_model)

# Flatten the output of the VGG16 model because it is from a
# convolutional layer.
new_model.add(Flatten())

# Add a dense (aka. fully-connected) layer.
# This is for combining features that the VGG16 model has
# recognized in the image.
new_model.add(Dense(512, activation='relu'))

# Add a dropout-layer which may prevent overfitting and
# improve generalization ability to unseen data e.g. the test-set.
new_model.add(Dropout(0.5))

# Add the final layer for the actual classification.
new_model.add(Dense(6, activation='softmax'))

In [78]:
def print_layer_trainable():
    for layer in conv_model.layers:
        print("{0}:\t{1}".format(layer.trainable, layer.name))

In [79]:
print_layer_trainable()

True:	input_2
True:	block1_conv1
True:	block1_conv2
True:	block1_pool
True:	block2_conv1
True:	block2_conv2
True:	block2_pool
True:	block3_conv1
True:	block3_conv2
True:	block3_conv3
True:	block3_pool
True:	block4_conv1
True:	block4_conv2
True:	block4_conv3
True:	block4_pool
True:	block5_conv1
True:	block5_conv2
True:	block5_conv3
True:	block5_pool


In [80]:
conv_model.trainable = False

In [81]:
for layer in conv_model.layers:
    layer.trainable = False

In [83]:
print_layer_trainable()

False:	input_2
False:	block1_conv1
False:	block1_conv2
False:	block1_pool
False:	block2_conv1
False:	block2_conv2
False:	block2_pool
False:	block3_conv1
False:	block3_conv2
False:	block3_conv3
False:	block3_pool
False:	block4_conv1
False:	block4_conv2
False:	block4_conv3
False:	block4_pool
False:	block5_conv1
False:	block5_conv2
False:	block5_conv3
False:	block5_pool


In [96]:
new_model.compile("rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])

In [97]:
new_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
model_6 (Model)              (None, 7, 7, 512)         14714688  
_________________________________________________________________
flatten_2 (Flatten)          (None, 25088)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 512)               12845568  
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 3078      
Total params: 27,563,334
Trainable params: 12,848,646
Non-trainable params: 14,714,688
_________________________________________________________________


In [94]:
X_train.shape

(420, 224, 224, 3)

Para efecto de aguilidad en el desarrollo del modelo, se realizara una corrida con 2 epochs

In [99]:
new_model.fit(X_train,Y_train,epochs=2,verbose=2)

Epoch 1/2
 - 394s - loss: 12.0549 - acc: 0.2238
Epoch 2/2
 - 382s - loss: 10.2679 - acc: 0.3286


In [101]:
# make predictions for testing set
y_pred_tran = new_model.predict_classes(X_test)
y_pred_tran

array([5, 4, 5, 5, 5, 2, 5, 4, 5, 5, 2, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5,
       5, 2, 5, 2, 5, 5, 5, 5, 5, 5, 2, 5, 4, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 4, 5, 2, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       2, 4, 4, 4, 5, 5, 5, 2, 2, 5, 4, 2, 4, 5, 5, 4, 5, 5, 2, 5, 5, 5, 5,
       5, 5, 2, 2, 2, 5, 5, 5, 2, 2, 5, 5, 5, 4, 5, 2, 2, 4, 5, 4, 5, 5, 5,
       2, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 1, 5, 5,
       5, 5, 2, 2, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 2, 5, 5, 5, 4, 5, 5, 5,
       2, 5, 4, 5, 5, 5, 2, 5, 5, 2, 2, 5, 4, 5, 2, 5, 2, 5, 2])

In [106]:
Y_test_new=Y_test.argmax(axis=1)
Y_test_new

array([1, 4, 5, 0, 1, 2, 0, 4, 0, 3, 0, 1, 1, 5, 3, 2, 0, 2, 1, 0, 0, 5, 5,
       5, 3, 5, 0, 1, 5, 4, 5, 1, 0, 2, 1, 4, 1, 5, 4, 2, 3, 0, 5, 5, 0, 1,
       4, 1, 0, 4, 2, 2, 1, 5, 5, 3, 2, 1, 1, 1, 0, 1, 3, 5, 5, 0, 5, 5, 0,
       3, 3, 0, 4, 3, 4, 5, 3, 2, 5, 4, 2, 4, 5, 3, 0, 0, 1, 2, 3, 2, 2, 5,
       0, 3, 2, 2, 2, 0, 4, 0, 0, 2, 5, 3, 0, 4, 1, 2, 2, 4, 1, 4, 5, 5, 3,
       3, 3, 1, 4, 4, 1, 0, 3, 5, 1, 1, 5, 2, 5, 4, 0, 5, 1, 1, 4, 1, 0, 0,
       2, 0, 0, 2, 1, 0, 4, 1, 3, 4, 0, 0, 5, 5, 3, 3, 5, 2, 0, 4, 1, 0, 3,
       2, 0, 4, 3, 1, 2, 2, 5, 3, 2, 2, 5, 4, 1, 0, 4, 0, 0, 2])

In [107]:
print('The accuracy of the model is ',(y_pred_tran==Y_test_new).mean())

The accuracy of the model is  0.411111111111


### A continuacion se procedera con el Fine-Tune del modelo

Se realizara la configuracion del modelo para permitir la modificacion de los pesos del modelo pre-entrenado y adicionalmente se configuraran las capas adicionales que se configuraron anteriomente.

In [108]:
conv_model.trainable = True

In [109]:
for layer in conv_model.layers:
    # Boolean whether this layer is trainable.
    trainable = ('block5' in layer.name or 'block4' in layer.name)
    
    # Set the layer's bool.
    layer.trainable = trainable

In [110]:
print_layer_trainable()

False:	input_2
False:	block1_conv1
False:	block1_conv2
False:	block1_pool
False:	block2_conv1
False:	block2_conv2
False:	block2_pool
False:	block3_conv1
False:	block3_conv2
False:	block3_conv3
False:	block3_pool
True:	block4_conv1
True:	block4_conv2
True:	block4_conv3
True:	block4_pool
True:	block5_conv1
True:	block5_conv2
True:	block5_conv3
True:	block5_pool


In [111]:
rmsprop=RMSprop(lr=0.001)

In [113]:
new_model.compile(optimizer=rmsprop, loss="categorical_crossentropy", metrics=["accuracy"])

In [114]:
new_model.fit(X_train,Y_train,epochs=2,verbose=2)

Epoch 1/2
 - 626s - loss: 13.0843 - acc: 0.1857
Epoch 2/2
 - 604s - loss: 13.4317 - acc: 0.1667


In [ ]:
# make predictions for testing set
y_pred_ft = new_model.predict_classes(X_test)

In [116]:
print('The accuracy of the model is ',(y_pred_ft==Y_test_new).mean())

The accuracy of the model is  0.172222222222


### 3.1. Modelo con Fine Tuning CONCLUSIONES

Al correr los dos modelos y comparar los respectivos Accuracy, se peude evidenciar que el modelo Fine-Tune tiende a perder casi un 50% de Accuracy respecto al modelo de Transfer Learning. Esto se puede dar debiado a que el modelo de Fine-Tune puede llegar a generar Overfitting y no funcionar tener un buen rendimiento en datos de test.

### CONCLUSIONES GENERALES

* Para este conjunto de datos y partiendo de la configuración plasmada en los modelos desarrollados por el equipo, se evidencia que el modelo VGG16 por si solo es un excelente predictor. Con los modelos de transfer learning se evidencia que se puede tener resultados similares o mejores en algunas corridas. Pero para el modelo de Fine-tune definitivamente no se evidencia un buen rendimiento a la hora de predecir, de hecho computacionalmente es mas lento debido a la configuracion de velocidad de aprendizaje, pero hablando netamene de la medida de rendimiento, su Accuracy es bastante menor a los obtenidos por los modelos anteriores.